AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket with specific configurations.

Parameters:
  Environment:
    Type: String
    Description: The environment
    Default: free
  Project:
    Type: String
    Description: The project name
    Default: belkeeper
  Region:
    Type: String
    Description: The AWS region
    Default: eu-central-1

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Project}-${Environment}-${Region}-terraform-tfstate-files'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub 'arn:aws:s3:::${Project}-${Environment}-${Region}-terraform-tfstate-files'
              - !Sub 'arn:aws:s3:::${Project}-${Environment}-${Region}-terraform-tfstate-files/*'
            Condition:
              Bool:
                aws:SecureTransport: false

Outputs:
  BucketName:
    Description: The name of the S3 bucket.
    Value: !Ref S3Bucket